### ISSUE TITLE
Details zum ToDo Bearbeiten Button ohne Funktion

### ISSUE THREAD

**Issue by Lu-Event** [MysteryCode/de.mysterycode.wcf.toDo#10]
Am Mac sowohl mit Safari Version 9.1.3 (11601.7.8) als auch mit Firefox 50.1.0 ist der Button Bearbeiten in der Detail Seite ohne Funktion. Er taucht zwar auf, lässt sich auch Hovern aber nix passiert.

Verwendung von PHP 7.0

**Comment by mutec** [comment]
Welchen Entwicklungszweig verwendest du? Im Vortex-Branch kann ich das aktuell nicht reproduzieren und würde es damit als erledigt abhaken.
