### ISSUE TITLE
Fehlendes Icon Inhalt melden

### ISSUE THREAD

**Issue by Lu-Event** [MysteryCode/de.mysterycode.wcf.toDo#7]
Auf der Seite Details zum ToDo fehlt ein Icon.

![bildschirmfoto 2017-01-27 um 19 25 17](https://cloud.githubusercontent.com/assets/5623224/22382547/67c98902-e4c6-11e6-9722-3b814ef7a6e8.png)

**Comment by mutec** [comment]
fixed by 96b14095809eca05fd84756ae77966e8047fbd84
